# Generated by Django 5.0.3 on 2024-03-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(db_index=False, max_length=250),
        ),
    ]
